#+title: Academia
#+AUTHOR: En logger
#+Date: 2023-07-22
#+HUGO_SECTION: archives/2023
#+hugo_auto_set_lastmod: t
#+hugo_draft: t

* Some bullshit article
What do you think when you think of academia? I have no idea. I do not even care. The idea around the academia is different for everyone. Therefore, I must give a shout-out to all the kind professors, teachers and staff who can keep this thing going since age millenia. But this post is not to praise those people who actually make academia a tolerable place. Not to say it is really refreshing to be in a position where you can easily explore any topic you like. Also, did I metion you will be tenured as professor? Once you are, no one can fire you and you get to do whatever your heart wants. Isn't that lucruative. The pristine ground where everyone is enjoys what they truly care.

Or that is what I thought before seeing the elites work. I am not taking about the average academic because I do not have any perspective on how that works. I am talking about the elitism that is present in the academia. So what is this about? It is about ego, competition, nerdiness and the ability to come on top of another. It is about onslaught and bloodbath that happens when running around a deadline. It is about those moments when you want to quit but can't. It is about persistence and continuing into something.

**Disclaimer**: /I am not a PhD graduate. I hate the idea of academia and the amount of freedom these academics have gained over the years. Also another fact where I come from technological background. Therefore, whatever I have here is going to extremely biased to my personal experience. It is not going to be true for everyone./

Just yesterday I read this article on how science is failing in modern days. Of course the cost of being a researcher it too damn high. Try to live a life without a job and you will know. Hence pursuing research is almost impossible without having a PhD. Now comes the issue. We are 8 billion people and there are only so many academia. Not everyone can go to the top and the ambition and fire you have won't take you any places. The inspirations and aspirations you heard, they are bullshit. Your motivation is also trash. Well if you have grades that is a different story. Or your side project is the worlds top research that is also different case. For an average joe like me, this whole thing is futile and meaningless.
** Getting In
Academia runs a ego of a dude. I am  not joking when I mention it. Not everyone is egoistic hence I mentioned it on the top. This is only the negative side. Often times the researcher at the so called top venues are the most crackhead and egoistic down to their feet. Anything that is less than elite will be considered trash. You have trash grades in your studies, you are trash. You won't even hear back from these dudes. Oh you might probably thinking that they don't have time reply because they are group leader. Or they might be taking a lot of time to reply because they are flooded with the messages.

These are genuinely true. All these professors are flooded with the messages. But during any off seasons try to reach out to them and attack their expertise. Make sure to add "your field sucks" kind of vibe and be prepared to hear a reply within 2 hours. Think about it, when you write a genuine email asking for a position and evaluation, they can't reply. The moment you attack what they do, you hear it back. Why does this work? It's cause their /ego/ is hurt, you dummy!

Say you feel you are talented enough to understand complicated stuff. You are not the best at it but you can get away through it. You know your limitations and you can learn/ask for help. Now the funny thing is that all the papers that come out of the top academic venue, all of them are not the best. If you read through these, you feel like even you could have done it. These days the top AI venues need access to GPU to get a "shiny" papers. Nothing else. It is not difficult to do what they do. Everything is already out there. None of them rely on math or the optimization trick. They do something called as engineering. Math is figuring it out later. If you are skilled engineer, you might think you will have a shot at academia. Despite knowing the fact you are an average, you believe in your skills and you spent hours honing it.

But does it matter to the face of academics? You aren't genius. /You are out/. You don't have good grades. /You are out/. You can't do cutting edge research because /you prioritized your life over anything else/. It might not be same for any other field. But for something like graphics, vision and language, the richer your school is the better you have chances on building your career. You get to make mistakes often and the faster you did it, the better you learn.

Now, all of this is being gatekeeped by one fucking ego maniac because he thinks you are trash. Hey, you might be trash but should they be given this authority? They don't allow you to fail at research. This is the sad reality. How can there be learning when all you are doing in life is acing everything straight out. How is this even possible? It's easy to pass through the exams. All you need is to figure out the pattern they ask the question and be good at answering them in that way. If you don't believe me try it in your uni. /Grades are important of academia./

** Your interest

Congratulations you got in. Great now what? You think you might be able to continue the research on your interest. Sure, if you got with the same advisor who you applied for. But do you really think that you are going to have 100% alignment with the idea?

This is where the quality of your supervisor really matters. If they are assholes, you are done. You will be slaving your life exploring what they think might be interesting. Good luck getting any help from your advisor/supervisor. Why would they care on your interest?

If they are caring and supportive, then you will have the best times of your life. Depending on the lab you might face different situations. I know a person who was accepted but got fired because they weren't productive enough. And it is coming from an elite institute. /Think about, a professor firing a  PhD student cause they aren't productive enough./ Like what the actual fuck. How does that even make sense?  Well in some countries /PhD/ is a /job./ But wasn't the whole point of PhD doing research? Turns out not. It is about boosting the H-index of your professor by publishing enough paper so that they can keep the cycle running.

I have't mentioned the fact that most who do PhD are depressed. They are less payed for the same role they could do in industry. Even after graduation you will have to compete with other PhD graduates for the same position. Think about it, there are only few positions and you are out there competing the graduates from around the world. Does it really make sense to stand all these abuses and depression episodes to get a qualification where you only have slight chance of doing better than everyone else?

** Message
The only way for you to continue a PhD in truly and independent way is to get a external funding and have an affliation with a kind person at the academia. Otherwise the whole thing is just not gonna work. The reason is very simple, doing anything extra-ordinary is difficult and hard. Thinks take time and you require a way to sustain yourself. Also you are at the edge thus everything else is unknown. This makes it even scary and depressing. Because you might be discovering it together with the professor for the first time. They only have good idea and can give hints. But still, not everyone is right. No one believed in Hinton until it worked.
