#+title: Confidence
#+AUTHOR: En logger
#+Date: 2023-07-22
#+HUGO_SECTION: archives/2023
#+hugo_auto_set_lastmod: t
#+hugo_draft: t

* Confidence
Yes, if you have if in a healthy amount, you are constantly learning and improving. There is some positive outlook to life. However, if you are lacking it then you are left with a inability to execute. There is a deep paralysis that lingers around you and catches you when you are about to do  something. Even if you were confident that you could pull it off, it might happen that you are not able to execute it. The issue with confidence is that it attacks your motivation. I have seldom seen an in-confident person who is ever motivated. There is something direly wrong with this thing. It sucks the life out of you.

* Trust
Wow, trust is something that is associated with the confidence. If you are confident enough, you can trust the system you are in. After all the you are already capable and the system will only facilitate the measures to assist you and you believe you can provide to the system too. But what would have if you start lose to trust on the system? Either you are left confused or motivated to start something on your own.

* Assistance
#+begin_quote
God helps those who help themselves.
#+end_quote
Now thing what will happen when a person loses the confidence in himself and the system? They are left wondering and in search of answers. But the entire system is designed to punish such wandering souls. Is it because the system has grown so big that they can't afford this? How is it possible to guide these people and even give them opportunities?

Such people are probably destined to be left out. Their emotions are definitely going to be invalidated and over time nothing can ever compound on these souls. The soceity that relies on having productive and high performing workers will never give a chance to such people. With a collected mass of such people, I am pretty sure there will be a revolution in near future. The numbers do not lie at all. It is apparant that there is something direly wrong in the system that it is not worth trusting anymore.

With the fabric of democracy relying on this system and the system failing to provide means to an end, it will only be matter of time before there is another uprising. Whatever it is future in uncertain.
